INSERT INTO `ship_type`(`id`, `name_en`, `name_jp`, `name_ch`, `name_tw`) VALUES ('DDE', '', '海防艦', '', ''), ('DD', 'Destroyer', '駆逐艦', '', ''), ('CL', 'Light cruiser', '軽巡洋艦', '', ''), 
('CLT', 'Torpedo Cruiser', '重雷装巡洋艦', '', ''), ('CA', 'Heavy Cruiser', '重巡洋艦', '', ''), ('CAV', 'Aviation Cruiser', '航空巡洋艦', '', ''), ('CVL', 'Light Aircraft Carrier', '軽空母', '', ''), 
('FBB', 'Fast Battleship', '', '', ''), ('BB', 'Battleship', '戦艦', '', ''), ('BBV', 'Aviation Battleship', '航空戦艦', '', ''), ('CV', 'Standard Aircraft Carrier', '正規空母', '', ''), 
('XBB', 'Super-Dreadnought Battleship', '超弩級戦艦', '', ''), ('SS', 'Submarine', '潜水艦', '', ''), ('SSV', 'Submarine Aircraft Carrier', '潜水空母', '', ''), ('AP', '', '補給艦', '', ''), 
('AV', 'Seaplane Tender', '水上機母艦', '', ''), ('LHA', 'Amphibious Assault Ship', '揚陸艦', '', ''), ('CVB', 'Armored Aircraft Carrier', '装甲空母', '', ''), ('AR', 'Repair Ship', '工作艦', '', ''), 
('AS', 'Submarine Tender', '潜水母艦', '', ''), ('CT', 'Training Cruiser', '練習巡洋艦', '', ''), ('AO', 'Supply Ship', '補給艦', '', '');

INSERT INTO `ship_class` (`name_en`, `name_jp`) VALUES ('Kamikaze', '神風型'),  ('Mutsuki', ''), ('Fubuki', ''), ('Ayanami', ''), ('Akatsuki', ''), ('Hatsuharu', ''), ('Shiratsuyu', ''), ('Asashio', ''), ('Kagerou', ''), ('Yuugumo', ''), ('Akizuki', ''), ('Shimakaze', ''), ('Maestrale', ''), ('Type 1934', ''), ('Tenryuu', ''), ('Kuma', ''), ('Nagara', ''), ('Sendai', ''), ('Agano', ''), ('Yuubari', ''), ('Ooyodo', ''), ('Katori', ''), ('Furutaka', ''), ('Aoba', ''), ('Myoukou', ''), ('Takao', ''), ('Mogami', ''), ('Tone', ''), ('Zara', ''), ('Admiral Hipper', ''), ('Kongou', ''), ('Fusou', ''), ('Ise', ''), ('Nagato', ''), ('Yamato', ''), ('Queen Elizabeth', ''), ('Vittorio Veneto', ''), ('Bismarck', ''), ('Iowa', ''), ('Houshou', ''), ('Ryuujou', ''), ('Ryuuhou', ''), ('Hiyou', ''), ('Shouhou', ''), ('Chitose', ''), ('Akagi', ''), ('Kaga', ''), ('Souryuu', ''), ('Hiryuu', ''), ('Shoukaku', ''), ('Unryuu', ''), ('Lexington', ''), ('Graf Zeppelin', ''), ('Aquila', ''), ('Taihou', ''), ('Junsen III Type (J3)', ''), ('Type-B (B1)', ''), ('Type-B Mod.2 (B3)', ''), ('I-400', ''), ('Type Kaidai VIa (KD6)', ''), ('RO-500', ''), ('Type 3 Submergence Transport Vehicle', ''), ('Type IXC', ''), ('Mizuho', ''), ('Akitsushima', ''), ('Commandant Teste', ''), ('Taigei', ''), ('Akitsu Maru', ''), ('Revised Kazahaya', ''), ('Akashi', '');
INSERT INTO `rarity` (`id`,`name`) VALUES (1,'Common'),(2,'Uncommon'),(3,'Rare'),(4,'Super Rare'),(5,''),(6,''),(7,''),(8,'');

INSERT INTO `servers` (`id`, `name_en`, `name_jp`) VALUES (1, 'Yokosuka Naval District', '横須賀鎮守府'), (2, 'Kure Naval District', '呉鎮守府'), (3, 'Sasebo Naval District', '佐世保鎮守府'), 
(4, 'Maizuru Naval District', '舞鶴鎮守府' ), (5, 'Ominato Guard District', '大湊警備府'), (6, 'Truk Anchorage', 'トラック泊地'), (7, 'Lingga Anchorage', 'リンガ泊地' ), (8, 'Rabaul Naval Base', 'ラバウル基地'), 
(9, 'Shortland Anchorage', 'ショートランド泊地'), (10, 'Buin Naval Base', 'ブイン基地'), (11, 'Tawi-Tawi Anchorage', 'タウイタウイ泊地'), (12, 'Palau Anchorage', 'パラオ泊地'), (13, 'Brunei Anchorage', 'ブルネイ泊地'), 
(14, 'Hitokappu Bay Anchorage', '単冠湾泊地'), (15, 'Paramushir Anchorage', '幌筵泊地'), (16, 'Sukumo Anchorage', '宿毛泊地'), (17, 'Kanoya Airfield', '鹿屋基地'), (18, 'Iwagawa Airfield', '岩川基地'), 
(19, 'Saiki Bay Anchorage', '佐伯湾泊地'), (20, 'Hashirajima Anchorage', '柱島泊地');